<a href="https://colab.research.google.com/github/GauraoM/Data-Analysis-for-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import sys

#### Basic Numpy

In [2]:
# Creating an array
array = np.array([1,2,3,4])

In [3]:
array[0]

1

In [4]:
# Multi indexing creating another numpy array
array[0],array[2],array[-1] 
# or array[[0,2,-1]]

(1, 3, 4)

In [6]:
# Array type
array.dtype

dtype('int64')

#### Dimension and Shapes

In [7]:
A = np.array([
              [1,2,3],
              [4,5,6]
              ])

In [8]:
A.shape

(2, 3)

In [9]:
A.ndim

2

#### Indexing and Slicing of Matrices

In [10]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
              ])

In [11]:
A[1]

array([4, 5, 6])

In [12]:
# Accesiing particular element from column of particular row
A[1][0]
# A[1,0]

4

In [13]:
A[1] = np.array([10,10,10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [14]:
A[2] = np.array([99])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#### Operations on array

In [15]:
A.sum()

333

In [16]:
A.std()

43.96463225012679

In [17]:
A.mean()

37.0

In [18]:
A.sum(axis=0) # Sum of each column

array([110, 111, 112])

#### Broadcasting and Vectroization

In [22]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [24]:
# Operation is applied to all the elements
a += 20
a

array([20, 21, 22, 23])

#### Boolean Array

In [26]:
a[[True, False,False,True]] # Selecting 1st and last element

array([20, 23])

In [28]:
a > 22
# a[a>22]

array([False, False, False,  True])

In [29]:
a[(a >=22) | (a != 0)]

array([20, 21, 22, 23])

#### Size of objects in Memory

In [31]:
# An inetger in python greater than 24 bytes
sys.getsizeof(1)

28

In [32]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [33]:
np.dtype(float).itemsize

8

#### Reshape

In [36]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Linespace

In [38]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])